repos:
- hooks:
  - args: ["--format=colored"]
    files: ^.pre-commit-config.yaml$
    id: yamllint
    name: Lint pre-commit config
  repo: git://github.com/adrienverge/yamllint.git
  rev: v1.17.0
- hooks:
  - id: nixpkgs-fmt
    name: Format .nix files
  repo: git://github.com/nix-community/nixpkgs-fmt
  rev: master
- hooks:
  - args: ["--format=tty"]
    id: shell-lint
  repo: git://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
# FIXME: Adds two trailing newlines
# - hooks:
#   - id: biber-autoformat
#   repo: git://github.com/katrielalex/biber-formatter
#   rev: v1
- hooks:
  - id: trailing-whitespace
  - exclude: ^VERSION$
    id: end-of-file-fixer
  - files: ^.pre-commit-config.yaml$
    id: check-yaml
    name: Check pre-commit config
  repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
