name: Publish PDF to site

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/tarball/master
    - uses: cachix/cachix-action@v8
      with:
        name: yurrriq
        skipPush: true
    - name: Clone gh-pages branch
      run: |
        git clone --quiet --branch gh-pages --depth 1 https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git site
        git -C site config user.name github-actions
        git -C site config user.email github-actions@users.noreply.github.com
    - name: Build PDF
      run: |
        nix-env -i jq -f '<nixpkgs>'
        cp -rv $(nix build --no-link --json | jq -r '.[0].outputs.out')/* site/
    - name: Publish to GitHub Pages
      run: |
        git -C site add --all .
        git -C site commit -m 'Publish to GitHub Pages'
        git -C site push --quiet https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
